name: PyTest

on:
  push:
    branches: [main, dev, design]
  pull_request:
    branches: [main, dev, design]

permissions:
  contents: read
  checks: write

jobs:
  test:
    name: Run & Report Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7

      - name: Setup Python
        uses: actions/setup-python@v7
        with:
          python-version: "3.13"

      - name: Install Hatch
        run: pipx install hatch

      - name: Run tests
        run: hatch test -- --junitxml=font/cover/TEST-${{ github.run_id }}.xml

      - name: Upload PyTest results
        uses: actions/upload-artifact@v7
        with:
          name: TEST-${{ github.run_id }}
          path: font/cover/TEST-${{ github.run_id }}.xml
          archive: false
        if: ${{ always() }}

      - name: Report PyTest
        uses: mikepenz/action-junit-report@v6
        if: always()
        with:
          check_name: PyTest Result
          report_paths: "font/cover/TEST-*.xml"
          detailed_summary: true # display detailed summary of the report
          include_passed: true # include passed tests in the results table
          group_suite: true # Group tests by suite name